import serial
import time

# Generated by chatGPT
# Define the serial port (may vary depending on your Raspberry Pi)

def read_microbit():
    serial_port = '/dev/ttyACM0'
    # Open the serial port (baudrate should match the micro:bit's baudrate)
    ser = serial.Serial(serial_port, baudrate=115200, timeout=1)
    data = ''
    while not data:
        data = ser.readline().decode().strip()
    ser.close()
    return data

