import serial
import time

# Generated by chatGPT
# Define the serial port (may vary depending on your Raspberry Pi)

def configure_microbit(port):
    """
    Set up the micro:bit
    """
    ser = serial.Serial(port, baudrate=115200, timeout=1)

    return ser

def read_microbit(ser):
    """
    Read micro:bit serial port
    """
    # Set up data buffer
    data = ""

    # Read buffer
    while not data:
        data = ser.readline().decode().strip()

    ser.reset_input_buffer()

    return data
